# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "122013bcb933149ebe63daff3560800b643884e2b11d29c95d02c38ff316b0f579c5";
    path = fetchzip {
      url = "https://github.com/timfayz/pretty/archive/d17634f6be0e0461e65accdb4cdabf4e17ccf0d1.tar.gz";
      hash = "sha256-0y73/IUfO+437DBEyTqX27GObGRdC9drqmhgQOTDs/Q=";
    };
  }
]
